{% raw -%}
---


- name: Instalar Docker GPG key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80
           id=58118E89F3A912897C070ADBF76221572C52609D
           state=present

- name: Añadir Docker al repositorio APT
  apt_repository: repo="deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main"
                  state=present

- name: Limpiar el antiguo repositorio de Docker si existe
  apt: name={{ item }}
       purge=yes
  with_items:
    - "lxc-docker*"
    - "docker.io*"
  ignore_errors: yes

- name: Instalar el paquete Docker
  apt: name=docker-engine
       update_cache=yes
       state=present
  notify: Iniciar Docker

- name: Crear el grupo Docker
  group: name=docker
         state=present

- name: Añadir {{ deploy_user }} al grupo Docker
  user: name={{ deploy_user }}
        groups=docker
        append=yes
  notify: Reiniciar Docker

- name: Instalar docker-compose
  pip: name=docker-compose
       state=present

{%- endraw %}
