---


- name: Instalar Nginx
  apt: name=nginx
       update_cache=yes
       state=installed
  tags: packages

- name: Asegurar la utilización de un grupo Diffie-Hellman fuerte
  command: openssl dhparam -out /etc/ssl/certs/dhparams.pem 2048
           creates=/etc/ssl/certs/dhparams.pem
  when: nginx_strong_dh_group is defined and nginx_strong_dh_group

- name: Asegurar que el servicio Nginx haya empezado
  service: name=nginx
           state=started
           enabled=yes
