{% raw -%}
---


- name: Suministrando el servidor web del proyecto {{ project_name }}
  hosts: dbservers
  become: yes
  become_user: root
  remote_user: "{{ deploy_user }}"
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - docker
    - nginx
    - certbot

{%- endraw %}
